site_name: zerolabs.cc

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  feature:
    tabs: true
  logo:
    icon: 'code'
 # 404 page
  static_templates:
    - 404.html

extra:
  search:
    language: 'fr'


repo_name: 'jorisserrand/zerolabs'
repo_url: 'https://github.com/j-serrand/zerolabs'

# Copyright
copyright:  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">L'ensemble du contenu du site zerolabs.cc</span> de
  <span xmlns:cc="http://creativecommons.org/ns#"
      property="cc:attributionName">Joris Serrand</span> est mis à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">licence Creative Commons Attribution <br />  Partage dans les Mêmes Conditions 4.0 International</a>.  <br />Made with ❤ in Albi

##############################################################################################
#     EXTENSIONS
##############################################################################################
markdown_extensions:
  - extra
  - tables
  - meta
  - fenced_code
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

##############################################################################################
#     MENUS
##############################################################################################
nav:
    - Home: index.md
    - tsti2d_sin :
      - Séquences : tsti2d/index.md
      - Linux :
        - Cours :
          - Introduction : tsti2d/linux/01-Intro.md
          - Utiliser le terminal : tsti2d/linux/02-Commandes_bash.md
          - Les permissions : tsti2d/linux/03-Permissions.md
        - Activités :
          - La ligne de commande P1 : tsti2d/linux/ACT1-ligne_comm_P1.md
          - La ligne de commande P2 : tsti2d/linux/ACT2-ligne_comm_P2.md
          - Les permissions : tsti2d/linux/ACT3-gerer_permissions.md
